name: Publish iOS App

on:
  push:
    branches:
      - ios-build-pipeline
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: macos-latest
    name: Build and Publish iOS App

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: cd ./'SORM Symposium' && npm install

      - name: Prebuild iOS app
        run: |
          # Build the iOS app using Expo
          npx expo build:ios --non-interactive --no-wait --release-channel production
          ls
